steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - frontend/Dockerfile
      - --build-arg
      - BACKEND_URL=${_BACKEND_URL}
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA
      - frontend

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA

substitutions:
  _REGION: asia-southeast2
  _AR_REPO: ecoguard-fe
  _IMAGE_NAME: ecoguard-fe
  _BACKEND_URL: https://example.com
