steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA
      - backend

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_IMAGE_NAME}:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: asia-southeast2
  _AR_REPO: ecoguard-be
  _IMAGE_NAME: ecoguard-be
