/**
 * Academic & Community Standard Indonesian Stopwords
 * Compiled from masdevid/ID-Stopwords and PySastrawi lists.
 */
export const INDON_STOPWORDS = new Set([
  'ada', 'adalah', 'adanya', 'adapun', 'agak', 'agaknya', 'agar', 'akan', 'akankah', 'akhir',
  'akhiri', 'akhirnya', 'aku', 'akulah', 'amat', 'amatlah', 'anda', 'andalah', 'antar', 'antara',
  'antaranya', 'apa', 'apaan', 'apabila', 'apakah', 'apalagi', 'apatah', 'arti', 'artinya', 'asal',
  'asalkan', 'atas', 'bagaikan', 'bagaimana', 'bagaimanakah', 'bagaimanapun', 'bagi', 'bagian', 'bahkan', 'bahwa',
  'bahwasanya', 'baik', 'bakal', 'bakalan', 'balik', 'banyak', 'bapak', 'baru', 'bawah', 'beberapa',
  'begitu', 'begitupun', 'bekerja', 'belakang', 'belakangan', 'belum', 'belumlah', 'benar', 'benarkah', 'benarlah',
  'berada', 'berakhir', 'beralasan', 'berikut', 'berikutnya', 'berjumlah', 'berkali-kali', 'berkata', 'berkehendak', 'berkeinginan',
  'berlalu', 'berlangsung', 'berlebihan', 'bermacam-macam', 'bersama', 'bersama-sama', 'berupa', 'beserta', 'betul', 'betulkah',
  'biasa', 'biasanya', 'bila', 'bilakah', 'bisa', 'bisakah', 'boleh', 'bolehkah', 'bolehlah', 'buat',
  'bukan', 'bukankah', 'bukanlah', 'bukannya', 'bulan', 'bung', 'cara', 'caranya', 'cukup', 'cukupkah',
  'cukuplah', 'cuma', 'dahulu', 'dalam', 'dan', 'dapat', 'dari', 'daripada', 'datang', 'dekat',
  'demi', 'demikian', 'demikianlah', 'dengan', 'depan', 'derajat', 'di', 'dia', 'diakhiri', 'diakhirinya',
  'dialah', 'diantara', 'diantaranya', 'diberi', 'diberikan', 'diberikannya', 'dibuat', 'dibuatnya', 'didapat', 'didatangkan',
  'digunakan', 'diibaratkan', 'diikuti', 'diingat', 'diingatkan', 'diinginkan', 'dijawab', 'dijelaskan', 'dijelaskannya', 'dikembangkan',
  'diketahui', 'diketahuinya', 'dikira', 'dikatakan', 'dikatakannya', 'dikira', 'dilakukan', 'dilalui', 'dilihat', 'dimaksud',
  'dimaksudkan', 'dimaksudkannya', 'dimulai', 'dimulailah', 'dimulainya', 'diminta', 'dimintai', 'dimisalkan', 'dimungkinkan', 'dini',
  'diri', 'dirinya', 'disini', 'disinilah', 'disisi', 'disitulah', 'ditambahkan', 'ditandai', 'ditandainya', 'ditanya',
  'ditanyai', 'ditanyakan', 'ditegaskan', 'ditujukan', 'ditunjuk', 'ditunjuki', 'ditunjukkan', 'ditunjukkannya', 'ditunjuknya', 'dituturkan',
  'dituturkannya', 'diucapkan', 'diucapkannya', 'diungkapkan', 'dua', 'dulu', 'empat', 'enggak', 'enggaknya', 'entah',
  'entahlah', 'guna', 'gunakan', 'hal', 'hampir', 'hanya', 'hanyalah', 'hari', 'harus', 'haruslah',
  'harusnya', 'hendak', 'hendaklah', 'hendaknya', 'hingga', 'ia', 'ialah', 'ibarat', 'ibaratnya', 'ibu',
  'ikut', 'ingat', 'ingat-ingat', 'ingin', 'inginkah', 'inginkan', 'ini', 'inikah', 'inilah', 'itu',
  'itukah', 'itulah', 'jadi', 'jadilah', 'jadinya', 'jangan', 'jangankan', 'janganlah', 'jauh', 'jawab',
  'jawaban', 'jawabnya', 'jelas', 'jelaskan', 'jelaslah', 'jelasnya', 'jika', 'jikalau', 'juga', 'jumlah',
  'jumlahnya', 'justru', 'kala', 'kalau', 'kalaulah', 'kalaupun', 'kali', 'kalian', 'kami', 'kamilah',
  'kamu', 'kamulah', 'kan', 'kapan', 'kapankah', 'kapanpun', 'karena', 'karenanya', 'kasus', 'kata',
  'katakan', 'katakanlah', 'katanya', 'ke', 'keadaan', 'kebetulan', 'kecil', 'kedua', 'keduanya', 'keinginan',
  'kelak', 'kelompok', 'keluar', 'keluar-masuk', 'keluaran', 'kembali', 'kemudian', 'kemungkinan', 'kemungkinannya', 'kenapa',
  'kepada', 'kepadanya', 'keseluruhan', 'keseluruhannya', 'keterangan', 'ketika', 'khusus', 'khususnya', 'kini', 'kinilah',
  'kira', 'kira-kira', 'kiranya', 'kita', 'kitalah', 'kok', 'kurang', 'lagi', 'lagian', 'lah',
  'lain', 'lainnya', 'lalu', 'lama', 'lamanya', 'langsung', 'lanjut', 'lanjutnya', 'lebih', 'lewat',
  'lima', 'luar', 'macam', 'maka', 'makanya', 'makin', 'malah', 'malahan', 'mampu', 'mampukah',
  'mana', 'manakala', 'manakah', 'manapun', 'masih', 'masihkah', 'masing', 'masing-masing', 'mau', 'maupun',
  'melainkan', 'melakukan', 'melalui', 'melihat', 'melihatnya', 'memang', 'memastikan', 'memberi', 'memberikan', 'membuat',
  'memulai', 'memungkinkan', 'meminta', 'memisahkan', 'mempunyai', 'memulai', 'memulailah', 'memulainya', 'menambahkan', 'menandai',
  'menanti', 'menanti-nanti', 'menanyakan', 'menanyai', 'mendapat', 'mendapatkan', 'mendatang', 'mendatangi', 'mendatangkan', 'menegaskan',
  'mengakhiri', 'mengapa', 'mengapakah', 'mengatakan', 'mengatakannya', 'mengenai', 'mengerjakan', 'mengetahui', 'menghendaki', 'mengibaratkan',
  'mengikuti', 'mengingat', 'mengingatkan', 'menginginkan', 'mengira', 'mengucapkan', 'mengucapkannya', 'mengungkapkan', 'menjadi', 'menjadikan',
  'menjabat', 'menjawab', 'menjelaskan', 'menuju', 'menunjuk', 'menunjukkan', 'menunjuknya', 'menurut', 'menuturkan', 'menyampaikan',
  'menyayangi', 'menyiapkan', 'menyesuaikan', 'menyatakan', 'menyebut', 'menyebutkan', 'menyebutkannya', 'menyusun', 'merasa', 'mereka',
  'merekalah', 'merupakan', 'meski', 'meskipun', 'meyakini', 'meyakinkan', 'minta', 'mirip', 'misal',
  'misalkan', 'misalnya', 'mula', 'mulai', 'mulailah', 'mulainya', 'mungkin', 'mungkinkah', 'nah', 'naik',
  'namun', 'nanti', 'nantinya', 'nyaris', 'nyata', 'nyatanya', 'oleh', 'olehnya', 'orang',
  'pada', 'padahal', 'padanya', 'pak', 'paling', 'panjang', 'pantas', 'para', 'pasti', 'pastilah',
  'penting', 'pentingnya', 'per', 'percuma', 'perlu', 'perlukah', 'perlulah', 'pernah', 'persoalan', 'pertama',
  'pertama-tama', 'pertanyaan', 'pihak', 'pihaknya', 'pukul', 'pula', 'pun', 'punya', 'rasa',
  'rasanya', 'rata', 'rupanya', 'saat', 'saatnya', 'saja', 'sajalah', 'saling', 'sama', 'sama-sama',
  'sambil', 'sampai', 'sana', 'sanalah', 'sangat', 'sangatlah', 'satu', 'saya', 'sayalah', 'se',
  'sebab', 'sebabnya', 'sebagai', 'sebagainya', 'sebagaimana', 'sebagian', 'sebagian besar', 'sebaliknya', 'sebanyak', 'sebelum',
  'sebelumnya', 'sebenarnya', 'seberapa', 'sebesar', 'sebetulnya', 'sebisanya', 'sebuah', 'sebut', 'sebutkan', 'sebutnya',
  'secara', 'secukupnya', 'sedang', 'sedangkan', 'sedikit', 'sedikitnya', 'segalanya', 'segera', 'seharusnya', 'sehingga',
  'sejak', 'sejarah', 'sejenak', 'sejumlah', 'sekadar', 'sekadarnya', 'sekali', 'sekali-kali', 'sekalian', 'sekaligus',
  'sekalipun', 'sekarang', 'sekaranglah', 'sekitar', 'sekitarnya', 'sekolah', 'sekurang-kurangnya', 'sekurangnya', 'sela', 'selain',
  'selaku', 'selalu', 'selama', 'selama-lamanya', 'selamanya', 'selanjutnya', 'selaras', 'seluruh', 'seluruhnya', 'semacam',
  'semakin', 'semampu', 'semampunya', 'semasa', 'semasih', 'semata', 'semata-mata', 'semestinya', 'semi', 'semisal',
  'sempat', 'semua', 'semuanya', 'semula', 'sendiri', 'sendirinya', 'sendirilah', 'seolah', 'seolah-olah', 'seorang',
  'sepanjang', 'sepantasnya', 'sepantasnyalah', 'seperti', 'sepertinya', 'sepihak', 'seputaran', 'sering', 'seringnya', 'serta',
  'serupa', 'sesaat', 'sesama', 'sesampai', 'sesampainya', 'sesekali', 'seseorang', 'sesuatu', 'sesuatunya', 'sesudah',
  'sesudahnya', 'setelah', 'setempat', 'setengah', 'seterusnya', 'setiap', 'setiba', 'setibanya', 'setidak-tidaknya', 'setidaknya',
  'setinggi', 'seusai', 'sewaktu', 'siap', 'siapa', 'siapakah', 'siapapun', 'sini', 'sinilah', 'situ',
  'situlah', 'suatu', 'sudah', 'sudahkah', 'sudahlah', 'supaya', 'tadi', 'tadinya', 'tahu', 'tak',
  'tambah', 'tambahnya', 'tampak', 'tampaknya', 'tanpa', 'tanya', 'tanyanya', 'tapi', 'tegas', 'tegasnya',
  'telah', 'tempat', 'tentang', 'tentu', 'tentulah', 'tentunya', 'tepat', 'terakhir', 'terasa', 'terbanyak',
  'terdahulu', 'terdapat', 'terdiri', 'terhadap', 'terhadapnya', 'teringat', 'terjadi', 'terjadilah', 'terjadinya', 'terkira',
  'terlalu', 'terlebih', 'terlihat', 'termasuk', 'ternyata', 'tersebut', 'tersebutnya', 'tertentu', 'tertuju', 'terutama',
  'tetap', 'tetapi', 'tiap', 'tidak', 'tidakkah', 'tidaklah', 'tiga', 'tinggi', 'toh', 'tunjuk',
  'turut', 'tutur', 'tuturnya', 'ucap', 'ucapnya', 'ujar', 'ujarnya', 'umum', 'umumnya', 'ungkap',
  'ungkapnya', 'untuk', 'untungnya', 'usah', 'usai', 'wadah', 'wajah', 'walau', 'walaupun', 'waktu',
  'waktunya', 'wilayah', 'ya', 'yaitu', 'yakin', 'yang'
]);

/**
 * Highly Comprehensive Indonesian Slang/Abbreviation Dictionary
 * Maps informal, social media, and SMS-styled Indonesian terms to formal root words.
 */
export const INDON_SLANG_MAP: Record<string, string> = {
  // Pronouns
  'gw': 'saya',
  'gua': 'saya',
  'gue': 'saya',
  'gwa': 'saya',
  'lu': 'Anda',
  'loe': 'Anda',
  'elo': 'Anda',
  'kamu': 'Anda',
  'lu orang': 'Anda sekalian',

  // Conjunctions & Prepositions
  'yg': 'yang',
  'kalo': 'jika',
  'kalw': 'jika',
  'karna': 'karena',
  'kerana': 'karena',
  'bcs': 'karena',
  'tp': 'tetapi',
  'tpi': 'tetapi',
  'dgn': 'dengan',
  'dg': 'dengan',
  'pd': 'pada',
  'dr': 'dari',
  'dri': 'dari',
  'ke': 'ke',
  'di': 'di',
  'utk': 'untuk',
  'bwt': 'untuk',
  'buat': 'untuk',
  'sm': 'sama',
  'sama': 'dengan',
  'spt': 'seperti',
  'seprti': 'seperti',

  // Adjectives & Emphasis
  'bgt': 'sangat',
  'banget': 'sangat',
  'parah': 'sangat parah',
  'cpt': 'cepat',
  'cepet': 'cepat',
  'lgsg': 'langsung',
  'dket': 'dekat',
  'deket': 'dekat',
  'sngt': 'sangat',
  'amat': 'sangat',
  'skali': 'sekali',
  'terlalu': 'sangat',

  // Negatives
  'ga': 'tidak',
  'gak': 'tidak',
  'ndak': 'tidak',
  'kaga': 'tidak',
  'kagak': 'tidak',
  'tack': 'tidak',
  'tdk': 'tidak',
  'g': 'tidak',

  // Nouns / Government / Citizen Context
  'min': 'petugas',
  'admin': 'petugas',
  'petugas': 'petugas',
  'gan': 'petugas',
  'bos': 'petugas',
  'sis': 'petugas',
  'lapor': 'melaporkan bahwa',
  'tolong': 'dimohon untuk segera',
  'pls': 'mohon',
  'please': 'mohon',
  'mohon': 'mohon',
  'aduan': 'laporan aduan',
  'keluhan': 'laporan aduan',

  // Technical & Civic specific mappers (Ensures nouns are properly structured)
  'mati total': 'tidak berfungsi sepenuhnya',
  'matot': 'tidak berfungsi sepenuhnya',
  'padam': 'tidak menyala',
  'rusak parah': 'mengalami kerusakan berat',
  'ancur': 'mengalami kerusakan berat',
  'hancur': 'mengalami kerusakan berat',
  'lubang besar': 'terdapat amblas jalan yang cukup membahayakan',
  'banjir': 'terjadi genangan air',
  'kebanjiran': 'terdampak genangan air',
  'tanggul jebol': 'kerusakan tanggul penahan air',
  'mampet': 'tersumbat penuh',
  'macet': 'kemacetan lalu lintas',
  'macet parah': 'kemacetan lalu lintas berat',
  'padat merayap': 'kepadatan lalu lintas merayap',
};
